# Copyright (c) 2020 Allan Mobley. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.

trigger:
  tags:
    include:
    - v*
  
pool:
  vmImage: 'ubuntu-latest'

steps:

# Specify a particular version of the .NET SDK
- task: UseDotNet@2
  displayName: 'Set SDK'
  inputs:
    packageType: sdk
    version: 3.1.201
    installationPath: $(Agent.ToolsDirectory)/dotnet

# Create the NuGet package file
- script: dotnet pack --configuration Release
  workingDirectory: src
  displayName: Pack Src

# Upload the NuGet package file to nuget.org
- task: NuGetCommand@2
  displayName: Push Src
  inputs:
    command: push
    packagesToPush: 'src/bin/Release/*.nupkg'
    nuGetFeedType: external
    publishFeedCredentials: 'Blazor Packages'